# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      env:
        description: 'env(prod | dev)'
        required: true
        default: 'dev'
      app:
        description: 'env(api | loop)'
        required: true
        default: 'api'
        
jobs:
  create_procfile:
    if: ${{ (github.event.inputs.env == 'prod' || github.event.inputs.env == 'dev') && (github.event.inputs.app == 'api' || github.event.inputs.app == 'loop') }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run create procfile
        run: |
          echo "web: yarn run start:${{ github.event.inputs.app }}:${{ github.event.inputs.env}}"
          echo "web: yarn run start:${{ github.event.inputs.app }}:${{ github.event.inputs.env}}" > Procfile
